### ISSUE TITLE
Pypi package description

### ISSUE THREAD

**Issue by DallasC** [LukeMathWalker/linfa-python#1]
Currently the description for `linfa` on `pypi` is empty. Since you are using `Poetry` to fix this you just need to update the `pyproject.toml` file to include the `long_description` or in poetry it's just called `readme`.

At the top of the file it should look like this
```toml
[tool.poetry]
name = "linfa"
version = "0.1.0"
authors = ["LukeMathWalker <rust@lpalmieri.com>"]
description = "Python bindings for the Rust crate linfa, a Rust machine learning framework."
readme = "README.md"
```
You can actually use any txt or markdown file so it doesn't have to be the main readme file.
Also, there are some other settings it might be nice to include such as `license`, `repository`, `hompage` (if we have one) etc..
You can find a full list of possible settings [here](https://python-poetry.org/docs/pyproject/)

I can go ahead and open a pull request with these changes but it might be quicker and easier for you to update them yourself since you know which settings are actually relevant
